data:
  dataset: breast_cancer_wisconsin
  dataset_url: https://huggingface.co/datasets/MLLab-TS/breast_cancer_wisconsin/resolve/main/dataset.csv
  target_column: diagnosis
experiment:
  tags:
  - breast_cancer_wisconsin
  name: breast_cancer_wisconsin
model:
  type: RandomForestClassifier
  n_estimators: 20
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 3
