data:
  dataset: car_eval_4
  dataset_url: https://huggingface.co/datasets/MLLab-TS/car_eval_4/resolve/main/dataset.csv
  target_column: target
experiment:
  tags:
  - car_eval_4
  name: car_eval_4
model:
  type: RandomForestClassifier
  n_estimators: 10
  min_impurity_decrease: 0.0
  max_features: 0.3
  max_depth: 10
